name: Desafio de Variáveis e Escopos

on: workflow_dispatch

env:
  APP_NAME: MeuApp

jobs:
  build_app:
    runs-on: windows-latest
    env:
      BUILD_VERSION: v1.0.0
    steps:
      - name: Passo 1
        run: |
          echo "App (global): $env:APP_NAME"
          echo "Build version: $env:BUILD_VERSION"
        shell: pwsh
      - name: Passo 2
        run: |
          $env:STEP_TEMP = "valor_temporario"
          echo "STEP_TEMP dentro: $env:STEP_TEMP"
        shell: pwsh
      - name: Passo 2b
        run: echo "STEP_TEMP fora: $env:STEP_TEMP"
        shell: pwsh
      - name: Passo 3
        run: echo "Usuario: ${{ github.actor }} | Repo: ${{ github.repository }} | SO: ${{ runner.os }}"
        shell: pwsh
      - name: Passo 4
        run: |
          $RANDOM_NUM = Get-Random -Maximum 32768
          "BUILD_HASH=$RANDOM_NUM" | Out-File -FilePath $env:GITHUB_ENV -Append
        shell: pwsh
      - name: Passo 5
        run: echo "Hash gerado: $env:BUILD_HASH"
        shell: pwsh

  deploy_app:
    runs-on: windows-latest
    steps:
      - name: Passo 6
        run: |
          echo "URL: ${{ vars.URL_AMBIENTE }}"
          echo "TOKEN: ${{ secrets.API_TOKEN_PROD }}"
        shell: pwsh
